import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    "eslint.config.mjs",
    "postcss.config.mjs",
    "e2e/**",
    "**/__tests__/**",
    "public/**",
  ]),

  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  {
    rules: {
      // === TypeScript strict ===
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-enum-comparison": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",
      "@typescript-eslint/no-unused-expressions": [
        "error",
        { allowShortCircuit: true, allowTaggedTemplates: true },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-empty-function": [
        "error",
        { allow: ["protected-constructors", "private-constructors"] },
      ],
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/prefer-ts-expect-error": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/restrict-plus-operands": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-var-requires": "error",
      "@typescript-eslint/no-meaningless-void-operator": "error",
      "@typescript-eslint/no-confusing-void-expression": "error",
      "@typescript-eslint/no-redundant-type-constituents": "error",
      "@typescript-eslint/non-nullable-type-assertion-style": "error",
      "@typescript-eslint/prefer-find": "error",
      "@typescript-eslint/prefer-for-of": "error",
      "@typescript-eslint/prefer-includes": "error",
      "@typescript-eslint/prefer-string-starts-ends-with": "error",
      "@typescript-eslint/prefer-regexp-exec": "error",
      "@typescript-eslint/prefer-return-this-type": "error",
      "@typescript-eslint/require-array-sort-compare": "error",
      "@typescript-eslint/unbound-method": "error",
      "@typescript-eslint/no-dynamic-delete": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/no-useless-empty-export": "error",
      "@typescript-eslint/triple-slash-reference": "error",

      // === Unused variables ===
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      // === JavaScript strict ===
      "eqeqeq": ["error", "always", { null: "never" }],
      "curly": ["error", "all"],
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-throw-literal": "off",
      "prefer-const": ["error", { destructuring: "all" }],
      "no-var": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-useless-return": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",
      "no-sparse-arrays": "error",
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "no-array-constructor": "error",
      "no-extend-native": "error",
      "no-iterator": "error",
      "no-proto": "error",
      "no-void": "error",
      "no-with": "error",
      "no-label-var": "error",
      "no-multi-str": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-script-url": "error",
      "no-shadow-restricted-names": "error",
      "no-undef-init": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-extra-boolean-cast": "error",
      "no-extra-semi": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-new-func": "error",
      "no-return-assign": ["error", "except-parens"],
      "no-return-await": "error",
      "no-sequences": "error",
      "no-unneeded-ternary": ["error", { defaultAssignment: false }],
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "yoda": ["error", "never", { exceptRange: true }],
      "prefer-arrow-callback": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "object-shorthand": ["error", "always"],

      // === React strict ===
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-undef": "error",
      "react/jsx-pascal-case": ["error", { allowAllCaps: true }],
      "react/no-array-index-key": "warn",
      "react/no-danger-with-children": "error",
      "react/no-deprecated": "error",
      "react/no-direct-mutation-state": "error",
      "react/no-find-dom-node": "error",
      "react/no-is-mounted": "error",
      "react/no-render-return-value": "error",
      "react/no-string-refs": "error",
      "react/no-unknown-property": "error",
      "react/require-render-return": "error",
      "react/self-closing-comp": "error",
      "react/style-prop-object": "error",
      "react-hooks/exhaustive-deps": "error",
      "react-hooks/set-state-in-effect": "error",

      // === Next.js strict ===
      "@next/next/no-img-element": "error",
      "@next/next/no-html-link-for-pages": "error",
      "@next/next/no-sync-scripts": "error",
      "@next/next/no-title-in-document-head": "error",
      "@next/next/no-unwanted-polyfillio": "error",
      "@next/next/no-typos": "error",
      "@next/next/no-css-tags": "error",
      "@next/next/no-document-import-in-page": "error",
      "@next/next/no-duplicate-head": "error",
      "@next/next/no-head-element": "error",
      "@next/next/no-head-import-in-document": "error",
      "@next/next/no-script-component-in-head": "error",

      // === Import strict ===
      "import/no-duplicates": "error",
      "import/no-self-import": "error",
      "import/no-useless-path-segments": "error",
      "import/no-deprecated": "error",
      "import/first": "error",
      "import/newline-after-import": ["error", { count: 1 }],
    },
  },

  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-console": "off",
    },
  },
]);

export default eslintConfig;
